INSERT INTO AUTHOR(ID, AUTHOR_NAME)
VALUES (1, 'Пушкин А. С.');
INSERT INTO AUTHOR(ID, AUTHOR_NAME)
VALUES (2, 'Кайт Том');
INSERT INTO AUTHOR(ID, AUTHOR_NAME)
VALUES (3, 'Макконел Стивен');

INSERT INTO GENRE(ID, GENRE_NAME)
VALUES (1, 'Стихи');
INSERT INTO GENRE(ID, GENRE_NAME)
VALUES (2, 'Программирование для профессионалов');