spring:
  datasource:
    url: jdbc:h2:mem:library

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true



  jackson:
    serialization:
      INDENT_OUTPUT: true

      fail-on-empty-beans: false

  data:
    rest:
      basePath: /datarest


management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

      defaults:
        enabled: true

logging:
  file:
    path: .
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

  logback:
    rollingpolicy:
      max-file-size: 1MB