spring:
  datasource:
    url: jdbc:h2:mem:library

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true

  jackson:
    serialization:
      INDENT_OUTPUT: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

      defaults:
        enabled: true

logging:
  file:
    path: .


  logback:
    rollingpolicy:
      max-file-size: 1MB