spring:
  datasource:
    url: jdbc:h2:mem:library

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

    show-sql: true
 