main:
  datasource:
    server: localhost
    port: 5432
    dbname: poem
    schema: public
    username: postgres
    password: 1

spring:
  datasource:
    url: jdbc:postgresql://${main.datasource.server}:${main.datasource.port}/${main.datasource.dbname}?ApplicationName=poem
    username: ${main.datasource.username}
    password: ${main.datasource.password}

  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
        show-sql: true