DELETE
FROM USR_ROLES;
DELETE
FROM ROLE;
DELETE
FROM POEM;
DELETE
FROM USR;

INSERT INTO ROLE(ROLE_NAME)
VALUES ('AUTHOR');

INSERT INTO ROLE(ROLE_NAME)
VALUES ('READER');

INSERT INTO ROLE(ROLE_NAME)
VALUES ('WRITER');

INSERT INTO ROLE(ROLE_NAME)
VALUES ('MODERATOR');

INSERT INTO USR(EMAIL, NAME, PASSWORD)
VALUES ('zina@yandex.ru', 'Зинаида', '123'),
       ('user@yandex.ru', 'user', '1'),
       ('sergey@yandex.ru', 'Сергей', '111');

INSERT INTO USR_ROLES(USER_ID, ROLE_ID)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (2, 2),
       (2, 3),
       (3, 2),
       (3, 3),
       (3, 4);

/*INSERT INTO POEM(TITLE)
VALUES ('Мое первое стихотворение');

INSERT INTO COMMENT(MODERATED, PUBLISH_TIME, TEXT, POEM_ID, ROOT_COMMENT_ID, USER_ID)
VALUES (FALSE, NULL, 'Очень классное стихотворение', 1, NULL, 1);

INSERT INTO COMMENT(MODERATED, PUBLISH_TIME, TEXT, POEM_ID, ROOT_COMMENT_ID, USER_ID)
VALUES (FALSE, NULL, 'Вообще ерунда', 1, NULL, 1);

INSERT INTO POEM_ELEMENT(POEM_ID)
VALUES (1),
       (1);

INSERT INTO POEM_PICTURE_ELEMENT(PICTURE, SCALE, ID)
VALUES ('\xDEADBEEF', 50, 1);

INSERT INTO POEM_TEXT_ELEMENT(CONTENT, ID)
VALUES ('Текст стихотворения', 2);*/