POST http://localhost:8080/api/comments
Content-Type: application/json

{
  "id": -1,
  "text": "Восторг, это крутоsdfsdafasdf;lds`kfmv zdslkf 'lsajkd flkjsaf",
  "user": {
    "id": 2,
    "email": "user@yandex.ru",
    "name": "Sergey",
    "password": ""
  },
  "poem": {
    "id": 1,
    "title": "Мое первое стихотворение"
  },
  "publishTime": "2023-02-17T22:49",
  "moderated": false
}